---
apiVersion: v1
kind: Service
metadata:
  namespace: photoprism
  name: photoprism
  labels:
    app: photoprism
spec:
  selector:
    app: photoprism
  ports:
  - name: http
    port: 2342
    targetPort: 2342
    protocol: TCP
  type: ClusterIP
