---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: tailscale-quantum
spec:
  replicas: 1
  hostnamePrefix: tailscale-quantum
  tags: ["tag:quantum-router"]
  subnetRouter:
    advertiseRoutes:
      - "10.10.10.0/24"
  exitNode: true
