---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      version: "1.90.9"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 1h
  valuesFrom:
    - kind: Secret
      name: tailscale-operator-oauth
      valuesKey: client_id
      targetPath: oauth.clientId
      optional: false
    - kind: Secret
      name: tailscale-operator-oauth
      valuesKey: client_secret
      targetPath: oauth.clientSecret
      optional: false
  values:
    operatorConfig:
      hostname: quantum-talos-operator
