apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:90gem2fJShhGyXRaStXSn3g=,iv:+5Rg5WnuGOCkAIhoBezRtufmiNePJ9lXJ3GXJMm9ol8=,tag:2ZJxvFYe8qcnDuvSug0YMw==,type:str]
    client_secret: ENC[AES256_GCM,data:18sgmNINopoVIl5nF9LG4t4cp1yqr7nOv7uxu4e6OUbdeyODvRM39bpTVpvRUwj6X8grXQxPbjGpoyDDx18l,iv:nm3g2KiY65MUjyyUO5LHznd8D/TiytLu4H/gx8XILJc=,tag:3F8IBZnNujrMaI7NccRiNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjw3xzg4xdtqhww82knn78zwwrye3larq42qrdvnrvztcnpf94hsv899fc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTDB5NjBnNDBDcmpZY2JM
            ck1ud0hlRzJSR09SWFNnRjNLaVRFa3J3UVNVCjVvRVN4L3paUUhmSHBjNDRCNzJw
            THBGUDYxZXUyc0pnWjR2TXdXcjc3V2sKLS0tIHhyVW14d0ovZ0c1QnAxUVFSRzRl
            TTNXYzJrU0NOYThxdFVjQ3dPK2hYcjgKxQTOL5wrKk7Z7pMJDuM2xygpHpDdv7B8
            tT+RQxCcCYGjiJFBDsIWldXs195fItODXxb433S5defEnHeg3H555A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T03:12:47Z"
    mac: ENC[AES256_GCM,data:Mv6GIGIPuOjx76840pWHx/m/0cd9QCpKojXKMguNDGVe2Dw9bM/JkWbuhUi4X8MYOrxgbm5++KFGi6HKzX1iAEqn/trQbXcjmodkGBzTe7IG173AeH9FC27L5hiV/yWfh1insY2970QpBx7eu13/S4nEKOLsc0ditlogeIYkD8A=,iv:zkvZc6fRzHz7JMBmeJoRlxVBSbHhVLJIDZCv5woF0GY=,tag:kQ7vu9Z5tKWYRT6C+go5QQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
