---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
spec:
  blocks:
  - start: "10.10.10.50"
    stop: "10.10.10.99"
  serviceSelector:
    matchLabels:
      color: blue
